language: python
matrix:
  include:
      - python: 3.6
        env: TOXENV=py36
      - python: 3.7
        env: TOXENV=py37
        sudo: required # required for Python >= 3.7 (travis-ci/travis-ci#9069)
        dist: xenial # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      - python: 3.6
        env: TOXENV=pre-commit
install:
  - pip install tox
script: make test
